[__config__]
oldver = "aur_old.txt"
newver = "aur_new.txt"

# aur packages maintained by me

[assetfinder]
source = "github"
github = "tomnomnom/assetfinder"
use_max_tag = true
prefix = "v"

[awx]
source = "github"
github = "ansible/awx"
use_max_tag = true
prefix = "v"

[butane]
source = "github"
github = "coreos/butane"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-workspace-matrix]
source = "github"
github = "mzur/gnome-shell-wsmatrix"
use_latest_release = true
prefix = "v"

[google-tsunami-security-scanner]
source = "github"
github = "google/tsunami-security-scanner"
use_latest_release = true

[jmeter-plugins-manager]
source = "cmd"
cmd = "curl -Is https://jmeter-plugins.org/get/ | grep Location | sed 's:.*/::;s:.*-::;s:.jar::'"

[xssmap]
source = "github"
github = "secdec/xssmap"

[hadolint]
source = "github"
github = "hadolint/hadolint"
use_max_tag = true
prefix = "v"

[zoiper]
source = "cmd"
cmd = "curl 'https://www.zoiper.com/en/voip-softphone/download/zoiper5/for/linux' --header 'Cookie: PHPSESSID=' -J -v -o /dev/null 2>&1 | grep filename | sed -e 's/.*Zoiper5_//g' -e 's/_x86_64.tar.xz\"//g'"

[actionlint]
source = "github"
github = "rhysd/actionlint"
use_max_tag = true
prefix = "v"

[pumba]
source = "github"
github = "alexei-led/pumba"
use_max_tag = true
prefix = "v"

[dockle]
source = "github"
github = "goodwithtech/dockle"
use_max_tag = true
prefix = "v"

[ddosify]
source = "github"
github = "ddosify/ddosify"
use_max_tag = true

[dstp]
source = "github"
github = "ycd/dstp"
use_max_tag = true
prefix = "v"

[spotdl]
source = "github"
github = "spotDL/spotify-downloader"
use_max_tag = true
prefix = "v"
