[__config__]
oldver = "aur_old.txt"
newver = "aur_new.txt"

# aur packages maintained by me

[assetfinder]
source = "github"
github = "tomnomnom/assetfinder"
use_max_tag = true
prefix = "v"

[awx]
source = "github"
github = "ansible/awx"
use_max_tag = true

[butane]
source = "github"
github = "coreos/butane"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-workspace-matrix]
source = "github"
github = "mzur/gnome-shell-wsmatrix"
use_latest_release = true
prefix = "v"

[google-tsunami-security-scanner]
source = "github"
github = "google/tsunami-security-scanner"
use_latest_release = true

[xssmap]
source = "github"
github = "secdec/xssmap"

[zoiper]
source = "cmd"
cmd = "curl 'https://www.zoiper.com/en/voip-softphone/download/zoiper5/for/linux' --header 'Cookie: PHPSESSID=' -J -v -o /dev/null 2>&1 | grep filename | sed -e 's/.*Zoiper5_//g' -e 's/_x86_64.tar.xz\"//g'"

[pumba]
source = "github"
github = "alexei-led/pumba"
use_max_tag = true

[dockle]
source = "github"
github = "goodwithtech/dockle"
use_max_tag = true
prefix = "v"

[anteon]
source = "github"
github = "getanteon/anteon"
use_latest_release = true
prefix = "selfhosted-"

[dstp]
source = "github"
github = "ycd/dstp"
use_max_tag = true
prefix = "v"

[spotdl]
source = "pypi"
github = "spotdl"

[docker-bench-security]
source = "github"
github = "docker/docker-bench-security"
use_max_tag = true
prefix = "v"

# [jmeter-plugins-manager]
# source = "cmd"
# cmd = "curl -Is https://jmeter-plugins.org/get/ | grep Location | sed -e 's/.*jmeter-plugins-manager-//g' -e 's/.jar//'"

[android-sdk-build-tools]
source = "cmd"
cmd = "curl -s https://developer.android.com/tools/releases/build-tools | grep -oP 'Build Tools, Revision [0-9.]+(?!-rc)' | sed 's/Build Tools, Revision //' | head -n 1"

[opkssh]
source = "github"
github = "openpubkey/opkssh"
use_max_tag = true
prefix = "v"

[cadvisor]
source = "github"
github = "google/cadvisor"
use_latest_release = true
prefix = "v"

[multi-git-status]
source = "github"
github = "fboender/multi-git-status"
use_latest_release = true
