[__config__]
oldver = "aur_old.txt"
newver = "aur_new.txt"

# aur packages maintained by me

[assetfinder]
source = "github"
github = "tomnomnom/assetfinder"
use_max_tag = true
prefix = "v"

[awx]
source = "github"
github = "ansible/awx"
use_max_tag = true
prefix = "v"

[fcct]
source = "github"
github = "coreos/fcct"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-workspace-matrix]
source = "github"
github = "mzur/gnome-shell-wsmatrix"
use_latest_release = true
prefix = "v"

[google-tsunami-security-scanner]
source = "github"
github = "google/tsunami-security-scanner"
use_latest_release = true

[jmeter-plugins-manager]
source = "cmd"
cmd = "curl -Is https://jmeter-plugins.org/get/ | grep Location | sed 's:.*/::;s:.*-::;s:.jar::'"

[obfs4proxy]
source = "github"
github = "Yawning/obfs4"
use_max_tag = true
prefix = "obfs4proxy-"

[tor-browser]
source = "aur"
github = "tor-browser"

[xssmap]
source = "github"
github = "secdec/xssmap"

[dash-to-dock]
source = "github"
github = "micheleg/dash-to-dock"

[vim-markdown]
source = "github"
github = "plasticboy/vim-markdown"

[hadolint]
source = "github"
github = "hadolint/hadolint"
