[__config__]
oldver = "old.txt"
newver = "new.txt"

# aur maintained by me

[assetfinder]
source = "github"
github = "tomnomnom/assetfinder"
use_max_tag = true

[fcct]
source = "github"
github = "coreos/fcct"
use_max_tag = true

[gnome-shell-extension-workspace-matrix]
source = "github"
github = "mzur/gnome-shell-wsmatrix"
use_max_tag = true

[google-tsunami-security-scanner]
source = "github"
github = "google/tsunami-security-scanner"
use_max_tag = true

[jmeter-plugins-manager]
source = "github"
github = "undera/jmeter-plugins"

[obfs4proxy]
source = "github"
github = "Yawning/obfs4"
use_max_tag = true

[tor-browser]
source = "aur"
github = "tor-browser"

[xssmap]
source = "github"
github = "secdec/xssmap"
