[__config__]
oldver = "others_old.txt"
newver = "others_new.txt"

# other packages i need

[ocserv]
source = "cmd"
cmd = "curl -s ftp://ftp.infradead.org/pub/ocserv/ | awk '{print $9}' | tail -n 1 | sed 's:.*-::;s:.tar.*::'"

[node_exporter]
source = "github"
github = "prometheus/node_exporter"
use_max_tag = true

[grafana_dashboard_1860]
source = "cmd"
cmd = "curl -s 'https://api.github.com/repos/rfrail3/grafana-dashboards/commits?path=prometheus/node-exporter-full.json&page=1&per_page=1' | jq -r '.[0].commit.committer.date'"

[thelounge]
source = "aur"
github = "thelounge"
