[__config__]
oldver = "others_old.txt"
newver = "others_new.txt"

# other packages i need

[ocserv]
source = "cmd"
cmd = "curl -s ftp://ftp.infradead.org/pub/ocserv/ | awk '{print $9}' | tail -n 1 | sed 's:.*-::;s:.tar.*::'"

[node_exporter]
source = "github"
github = "prometheus/node_exporter"
use_latest_release = true

[grafana_dashboard_1860]
source = "cmd"
cmd = "curl -s https://grafana.com/api/dashboards/1860/revisions | jq -r '.items | last | .revision'"

[thelounge]
source = "aur"
github = "thelounge"

[cloudflare_ipv4]
source = "cmd"
cmd = "curl 'https://api.cloudflare.com/client/v4/ips' -s | jq -r '.result.etag'"

[nginx-vod-module]
source = "github"
github = "kaltura/nginx-vod-module"
use_max_tag = true

[fluent-plugin-elasticsearch]
source = "gems"
github = "fluent-plugin-elasticsearch"

[elasticsearch-xpack]
source = "gems"
github = "elasticsearch-xpack"

[fluent-plugin-prometheus]
source = "gems"
github = "fluent-plugin-prometheus"

[query-exporter]
source = "github"
github = "albertodonato/query-exporter"
use_max_tag = true
prefix = ""

[iptables-persistent-deb10]
source = "cmd"
cmd = "curl -s http://deb.debian.org/debian/pool/main/i/iptables-persistent/ | grep 'deb10' | tail -1 | sed 's/.*netfilter-persistent_//' | sed 's/_all.*//'"

[healthchecks]
source = "github"
github = "healthchecks/healthchecks"
prefix = ""
use_max_tag = true
