---
name: nvchecker
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:

  nvchecker:
    name: nvchecker
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull base image.
        run: docker pull quay.io/aminvakil/archlinux:nvchecker

      - name: Run a container of base image and mount package on it.
        run: |
          container_id=$(mktemp)
          docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v "${PWD}":/nvchecker quay.io/aminvakil/archlinux:nvchecker > "${container_id}"
          echo "container_id=$container_id" >> $GITHUB_ENV

      - name: Nvcheck!
        run: |
          docker exec "$(cat ${container_id})" nvchecker -c /nvchecker/nvchecker.toml
          nvcmp_output=$(docker exec "$(cat ${container_id})" nvcmp -c /nvchecker/nvchecker.toml)
          if [[ $nvcmp_output ]]; then HAS_CHANGED='true' ; fi
          echo "HAS_CHANGED=$HAS_CHANGED" >> $GITHUB_ENV
          echo 'nvcmp_output<<EOF' >> $GITHUB_ENV
          echo $nvcmp_output >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create Issue.
        if: env.HAS_CHANGED == 'true'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Stop and remove container forcefully.
        run: docker rm -f "$(cat ${container_id})"
