---
name: nvchecker
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:

  nvcheck:
    name: nvcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull base image.
        run: docker pull quay.io/aminvakil/archlinux:latest

      - name: Run a container of base image and mount package on it.
        run: |
          container_id=$(mktemp)
          docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v "${PWD}":/nvchecker quay.io/aminvakil/archlinux:latest > "${container_id}"
          echo "container_id=$container_id" >> $GITHUB_ENV

      - name: Install nvchecker
        run: docker exec "$(cat ${container_id})" pacman -S nvchecker --noconfirm

      - name: Nvchecker!
        run: docker exec "$(cat ${container_id})" nvchecker -c /nvchecker/nvchecker.toml

      - name: Stop and remove container forcefully.
        run: docker rm -f "$(cat ${container_id})"
