---
name: Others
'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:

  Others:
    name: Others
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Pull base image.
        run: docker pull quay.io/aminvakil/archlinux:latest

      - name: Run a container of base image and mount package on it.
        run: |
          container_id=$(mktemp)
          docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v "${PWD}":/nvchecker quay.io/aminvakil/archlinux:latest > "${container_id}"
          echo "container_id=$container_id" >> $GITHUB_ENV

      - name: pacman -Syu
        run: docker exec "$(cat ${container_id})" pacman -Syu --noconfirm

      - name: Install nvchecker and git.
        run: docker exec "$(cat ${container_id})" pacman -S nvchecker git jq --noconfirm

      - name: Nvcheck!
        run: |
          docker exec "$(cat ${container_id})" nvchecker -c /nvchecker/others.toml
          others_nvcmp_output=$(docker exec "$(cat ${container_id})" nvcmp -c /nvchecker/others.toml)
          if [[ $others_nvcmp_output ]]; then OTHERS_HAS_CHANGED='true' ; fi
          echo "OTHERS_HAS_CHANGED=$OTHERS_HAS_CHANGED" >> $GITHUB_ENV
          echo 'others_nvcmp_output<<EOF' >> $GITHUB_ENV
          echo $others_nvcmp_output >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          mv others_new.txt others_old.txt

      # - name: Create Others Issue.
      #   id: others-create-issue
      #   if: env.OTHERS_HAS_CHANGED == 'true' && github.event_name != 'pull_request'
      #   uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     update_existing: true
      #     filename: .github/OTHERS_ISSUE_TEMPLATE.md

      - name: Create Others Pull Request
        if: env.OTHERS_HAS_CHANGED == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.others_nvcmp_output }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: othersbump
          delete-branch: true
          title: 'Others Bump'
          body: ${{ env.others_nvcmp_output }}
          draft: false

      - name: Stop and remove container forcefully.
        run: docker rm -f "$(cat ${container_id})"
